import { trackEmailSent } from './analytics'

interface EmailData {
  to: string
  subject: string
  body: string
  html?: string
}

export const sendEmail = async (data: EmailData): Promise<{ success: boolean; message: string }> => {
  try {
    const mailtoLink = `mailto:${encodeURIComponent(data.to)}?subject=${encodeURIComponent(data.subject)}&body=${encodeURIComponent(data.body)}`
    
    window.location.href = mailtoLink
    
    await trackEmailSent()
    
    return {
      success: true,
      message: 'Email client opened successfully'
    }
  } catch (error) {
    console.error('Failed to send email:', error)
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to send email'
    }
  }
}

export const formatEmailBody = (content: Record<string, any>, title: string): string => {
  let body = `${title}\n${'='.repeat(title.length)}\n\n`
  
  const formatValue = (value: any, indent = 0): string => {
    const prefix = '  '.repeat(indent)
    
    if (Array.isArray(value)) {
      return value.map((item, index) => {
        if (typeof item === 'object') {
          return `${prefix}${index + 1}.\n${formatValue(item, indent + 1)}`
        }
        return `${prefix}• ${item}`
      }).join('\n')
    }
    
    if (typeof value === 'object' && value !== null) {
      return Object.entries(value).map(([key, val]) => {
        const formattedKey = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
        return `${prefix}${formattedKey}: ${formatValue(val, indent + 1)}`
      }).join('\n')
    }
    
    return `${value}`
  }
  
  Object.entries(content).forEach(([key, value]) => {
    const formattedKey = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
    body += `${formattedKey}:\n${formatValue(value, 1)}\n\n`
  })
  
  body += '\n---\nGenerated by Autism and Me - Evidence Based Practice for Autism Support\nhttps://autismandme.com'
  
  return body
}

export const createPrintableHTML = (content: string, title: string): string => {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            color: oklch(0.15 0 0);
        }
        h1 {
            font-family: 'Merriweather', Georgia, serif;
            font-size: 28px;
            margin-bottom: 20px;
            color: oklch(0.15 0 0);
            border-bottom: 3px solid oklch(0.55 0.15 150);
            padding-bottom: 10px;
        }
        h2 {
            font-family: 'Merriweather', Georgia, serif;
            font-size: 20px;
            margin-top: 30px;
            margin-bottom: 15px;
            color: oklch(0.15 0 0);
        }
        h3 {
            font-size: 16px;
            font-weight: 600;
            margin-top: 20px;
            margin-bottom: 10px;
            color: oklch(0.15 0 0);
        }
        p {
            margin-bottom: 15px;
        }
        .section {
            margin-bottom: 30px;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 2px solid oklch(0.85 0.01 150);
            text-align: center;
            font-size: 14px;
            color: oklch(0.45 0 0);
        }
        @media print {
            body {
                margin: 20px;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <div class="content">
        ${content.replace(/\n/g, '<br>')}
    </div>
    <div class="footer">
        <p>Generated by Autism and Me - Evidence Based Practice for Autism Support</p>
        <p>${new Date().toLocaleDateString('en-GB')}</p>
    </div>
</body>
</html>
  `
}
