import { formatDateForEmail, createSectionHeader, createTextDivider } from './email-export'

export interface EmailTemplate {
  subject: string
  body: string
}

const APP_SIGNATURE = `

${createTextDivider('-')}
Generated by Autism and Me
Evidence Based Practice for Autism Support
www.autismandme.com
${createTextDivider('-')}
`

export const createLessonScriptEmail = (data: {
  studentProfile: string
  learningGoal: string
  selectedEBPs: string[]
  sensorySupports: string
  communicationSupports: string
  assessmentApproach: string
  script: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Lesson Script - ${data.learningGoal.substring(0, 50)}`
  
  const body = `LESSON SCRIPT
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}

${createSectionHeader('STUDENT/GROUP PROFILE')}
${data.studentProfile}

${createSectionHeader('LEARNING GOAL')}
${data.learningGoal}

${createSectionHeader('EVIDENCE-BASED PRACTICES USED')}
${data.selectedEBPs.map((ebp, i) => `${i + 1}. ${ebp}`).join('\n')}

${createSectionHeader('SENSORY SUPPORTS')}
${data.sensorySupports}

${createSectionHeader('COMMUNICATION SUPPORTS')}
${data.communicationSupports}

${createSectionHeader('ASSESSMENT APPROACH')}
${data.assessmentApproach}

${createSectionHeader('LESSON SCRIPT')}
${data.script}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createChoose3EBPsEmail = (data: {
  studentName: string
  situation: string
  keyNeeds: string[]
  selectedEBPs: Array<{ name: string; rationale: string }>
  nextSteps: string
  reviewPlan: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Choose 3 EBPs Plan - ${data.studentName}`
  
  const body = `CHOOSE 3 EBPs PLAN
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}

${createSectionHeader('STUDENT/SITUATION')}
${data.studentName}
${data.situation}

${createSectionHeader('KEY NEEDS IDENTIFIED')}
${data.keyNeeds.map((need, i) => `${i + 1}. ${need}`).join('\n')}

${createSectionHeader('SELECTED EVIDENCE-BASED PRACTICES')}
${data.selectedEBPs.map((ebp, i) => `
${i + 1}. ${ebp.name}
   Rationale: ${ebp.rationale}
`).join('\n')}

${createSectionHeader('NEXT STEPS')}
${data.nextSteps}

${createSectionHeader('REVIEW PLAN')}
${data.reviewPlan}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createSensoryChecklistEmail = (data: {
  studentName: string
  completedBy: string
  observations: {
    visual: { seeks: string[]; avoids: string[]; notes: string }
    auditory: { seeks: string[]; avoids: string[]; notes: string }
    tactile: { seeks: string[]; avoids: string[]; notes: string }
    proprioceptive: { seeks: string[]; avoids: string[]; notes: string }
    vestibular: { seeks: string[]; avoids: string[]; notes: string }
    olfactoryGustatory: { seeks: string[]; avoids: string[]; notes: string }
  }
  recommendations: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Sensory Needs Checklist - ${data.studentName}`
  
  const formatSensoryCategory = (category: string, data: { seeks: string[]; avoids: string[]; notes: string }) => {
    return `
${category.toUpperCase()}:
  Seeks:
    ${data.seeks.length > 0 ? data.seeks.map(s => `• ${s}`).join('\n    ') : '• None noted'}
  
  Avoids:
    ${data.avoids.length > 0 ? data.avoids.map(s => `• ${s}`).join('\n    ') : '• None noted'}
  
  Additional Notes: ${data.notes || 'None'}
`
  }
  
  const body = `SENSORY NEEDS CHECKLIST
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}
Completed by: ${data.completedBy}

${createSectionHeader('SENSORY OBSERVATIONS')}
${formatSensoryCategory('Visual', data.observations.visual)}
${formatSensoryCategory('Auditory', data.observations.auditory)}
${formatSensoryCategory('Tactile', data.observations.tactile)}
${formatSensoryCategory('Proprioceptive', data.observations.proprioceptive)}
${formatSensoryCategory('Vestibular', data.observations.vestibular)}
${formatSensoryCategory('Olfactory/Gustatory', data.observations.olfactoryGustatory)}

${createSectionHeader('RECOMMENDATIONS')}
${data.recommendations}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createBehaviourCommunicationEmail = (data: {
  studentName: string
  observedBehaviour: string
  antecedent: string
  consequence: string
  possibleMessage: string
  unmetNeed: string
  relevantEBPs: string[]
  proposedSupports: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Behaviour as Communication Analysis - ${data.studentName}`
  
  const body = `BEHAVIOUR AS COMMUNICATION ANALYSIS
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}

CORE PRINCIPLE: All behaviour is communication. Our role is to understand the message and respond with appropriate supports.

${createSectionHeader('ABC ANALYSIS')}

ANTECEDENT (What happened before?):
${data.antecedent}

BEHAVIOUR (What did the student do?):
${data.observedBehaviour}

CONSEQUENCE (What happened after?):
${data.consequence}

${createSectionHeader('UNDERSTANDING THE COMMUNICATION')}

Possible Communication Message:
${data.possibleMessage}

Possible Unmet Need:
${data.unmetNeed}

${createSectionHeader('RELEVANT EVIDENCE-BASED PRACTICES')}
${data.relevantEBPs.map((ebp, i) => `${i + 1}. ${ebp}`).join('\n')}

${createSectionHeader('PROPOSED SUPPORTS')}
${data.proposedSupports}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createCoRegulationEmail = (data: {
  studentName: string
  context: string
  environmentalSupports: string[]
  adultPresenceStrategies: string[]
  sensorySupports: string[]
  predictabilityStrategies: string[]
  languageScripts: string[]
  additionalNotes: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Co-Regulation Strategies - ${data.studentName}`
  
  const body = `CO-REGULATION STRATEGIES PLAN
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}

${createSectionHeader('CONTEXT')}
${data.context}

${createSectionHeader('ENVIRONMENTAL SUPPORTS')}
${data.environmentalSupports.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${createSectionHeader('ADULT PRESENCE STRATEGIES')}
${data.adultPresenceStrategies.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${createSectionHeader('SENSORY SUPPORTS')}
${data.sensorySupports.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${createSectionHeader('PREDICTABILITY & PACING')}
${data.predictabilityStrategies.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${createSectionHeader('LANGUAGE SCRIPTS')}
${data.languageScripts.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${createSectionHeader('ADDITIONAL NOTES')}
${data.additionalNotes}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createTransitionSupportEmail = (data: {
  studentName: string
  transitionType: string
  transitionDetails: string
  stressPoints: string[]
  visualSupports: string[]
  rehearsalPlan: string
  socialNarrative: string
  communicationPlan: string
  reviewDate: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Transition Support Plan - ${data.studentName}`
  
  const body = `TRANSITION SUPPORT PLAN
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}

${createSectionHeader('TRANSITION DETAILS')}
Type: ${data.transitionType}
Details: ${data.transitionDetails}

${createSectionHeader('IDENTIFIED STRESS POINTS')}
${data.stressPoints.map((point, i) => `${i + 1}. ${point}`).join('\n')}

${createSectionHeader('VISUAL SUPPORTS')}
${data.visualSupports.map((support, i) => `${i + 1}. ${support}`).join('\n')}

${createSectionHeader('REHEARSAL PLAN')}
${data.rehearsalPlan}

${createSectionHeader('SOCIAL NARRATIVE')}
${data.socialNarrative}

${createSectionHeader('COMMUNICATION PLAN')}
With student: ${data.communicationPlan}

${createSectionHeader('REVIEW & ADJUSTMENT')}
Review Date: ${data.reviewDate}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createStudentAssessmentEmail = (data: {
  studentName: string
  completedBy: string
  responses: Array<{
    ebpName: string
    rating: string
    comments: string
  }>
  overallFeedback: string
  preferredSupports: string[]
  timestamp: number
}): EmailTemplate => {
  const subject = `Student Self-Assessment - ${data.studentName}`
  
  const body = `STUDENT SELF-ASSESSMENT
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}
Completed by: ${data.completedBy}

${createSectionHeader('RESPONSES TO EVIDENCE-BASED PRACTICES')}
${data.responses.map((response, i) => `
${i + 1}. ${response.ebpName}
   Rating: ${response.rating}
   Comments: ${response.comments || 'None provided'}
`).join('\n')}

${createSectionHeader('PREFERRED SUPPORTS')}
${data.preferredSupports.map((support, i) => `${i + 1}. ${support}`).join('\n')}

${createSectionHeader('OVERALL FEEDBACK')}
${data.overallFeedback}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createParentAssessmentEmail = (data: {
  studentName: string
  parentName: string
  responses: Array<{
    ebpName: string
    worksWell: string
    doesntWork: string
    homeContext: string
  }>
  priorities: string[]
  additionalInformation: string
  timestamp: number
}): EmailTemplate => {
  const subject = `Parent/Carer Assessment - ${data.studentName}`
  
  const body = `PARENT/CARER ASSESSMENT
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}
Completed by: ${data.parentName}

${createSectionHeader('RESPONSES TO EVIDENCE-BASED PRACTICES')}
${data.responses.map((response, i) => `
${i + 1}. ${response.ebpName}
   What works well: ${response.worksWell}
   What doesn't work: ${response.doesntWork}
   Home context: ${response.homeContext}
`).join('\n')}

${createSectionHeader('PRIORITIES FOR SCHOOL SUPPORT')}
${data.priorities.map((priority, i) => `${i + 1}. ${priority}`).join('\n')}

${createSectionHeader('ADDITIONAL INFORMATION')}
${data.additionalInformation}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createSchoolPlanEmail = (data: {
  studentName: string
  planType: string
  createdBy: string
  dailySchedule: string
  environmentalAdaptations: string[]
  communicationSupports: string[]
  sensoryBreaks: string[]
  socialSupports: string[]
  academicAccommodations: string[]
  emergencyProtocol: string
  teamMembers: string[]
  reviewDate: string
  timestamp: number
}): EmailTemplate => {
  const subject = `School Support Plan - ${data.studentName}`
  
  const body = `SCHOOL SUPPORT PLAN
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}
Plan Type: ${data.planType}
Created by: ${data.createdBy}

${createSectionHeader('DAILY SCHEDULE')}
${data.dailySchedule}

${createSectionHeader('ENVIRONMENTAL ADAPTATIONS')}
${data.environmentalAdaptations.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${createSectionHeader('COMMUNICATION SUPPORTS')}
${data.communicationSupports.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${createSectionHeader('SENSORY BREAKS')}
${data.sensoryBreaks.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${createSectionHeader('SOCIAL SUPPORTS')}
${data.socialSupports.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${createSectionHeader('ACADEMIC ACCOMMODATIONS')}
${data.academicAccommodations.map((item, i) => `${i + 1}. ${item}`).join('\n')}

${createSectionHeader('EMERGENCY PROTOCOL')}
${data.emergencyProtocol}

${createSectionHeader('TEAM MEMBERS')}
${data.teamMembers.map((member, i) => `${i + 1}. ${member}`).join('\n')}

${createSectionHeader('REVIEW')}
Review Date: ${data.reviewDate}

${APP_SIGNATURE}`

  return { subject, body }
}

export const createCombinedReportEmail = (data: {
  studentName: string
  parentAssessment?: any
  studentAssessment?: any
  schoolPlan?: any
  sensoryChecklist?: any
  behaviourAnalyses?: any[]
  timestamp: number
}): EmailTemplate => {
  const subject = `Comprehensive Support Report - ${data.studentName}`
  
  let body = `COMPREHENSIVE SUPPORT REPORT
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}

This report combines multiple assessments and plans to provide a holistic view of support needs and strategies.

`

  if (data.parentAssessment) {
    body += `${createSectionHeader('PARENT/CARER PERSPECTIVE')}
Completed by: ${data.parentAssessment.parentName}

Key Priorities:
${data.parentAssessment.priorities.map((p: string, i: number) => `${i + 1}. ${p}`).join('\n')}

`
  }

  if (data.studentAssessment) {
    body += `${createSectionHeader('STUDENT PERSPECTIVE')}
Preferred Supports:
${data.studentAssessment.preferredSupports.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n')}

Overall Feedback: ${data.studentAssessment.overallFeedback}

`
  }

  if (data.sensoryChecklist) {
    body += `${createSectionHeader('SENSORY PROFILE SUMMARY')}
Key sensory needs have been identified across multiple domains.
Detailed sensory checklist available in separate document.

`
  }

  if (data.schoolPlan) {
    body += `${createSectionHeader('CURRENT SCHOOL SUPPORT PLAN')}
Plan Type: ${data.schoolPlan.planType}
Review Date: ${data.schoolPlan.reviewDate}
Team Members: ${data.schoolPlan.teamMembers.length}

`
  }

  if (data.behaviourAnalyses && data.behaviourAnalyses.length > 0) {
    body += `${createSectionHeader('BEHAVIOUR COMMUNICATION ANALYSES')}
${data.behaviourAnalyses.length} behaviour analysis/analyses completed.
Key themes identified in separate documents.

`
  }

  body += `${createSectionHeader('RECOMMENDATIONS')}
This combined report should be reviewed collaboratively by the full support team, including the student and family where appropriate.

All supports should be:
• Evidence-based
• Student-centred
• Regularly reviewed and adjusted
• Implemented with dignity and autonomy

${APP_SIGNATURE}`

  return { subject, body }
}

export const createVRTransitionEmail = (data: {
  studentName: string
  scenario: string
  purpose: string
  duration: string
  successCriteria: string
  supportNeeded: string
  followUp: string
  timestamp: number
}): EmailTemplate => {
  const subject = `VR Transition Preparation - ${data.studentName}`
  
  const body = `VR TRANSITION PREPARATION PLAN
${createTextDivider('=')}

Generated: ${formatDateForEmail(data.timestamp)}
Student: ${data.studentName}

${createSectionHeader('VR SCENARIO DETAILS')}
Scenario: ${data.scenario}
Purpose: ${data.purpose}
Duration: ${data.duration}

${createSectionHeader('SUCCESS CRITERIA')}
${data.successCriteria}

${createSectionHeader('SUPPORT NEEDED')}
${data.supportNeeded}

${createSectionHeader('FOLLOW-UP PLAN')}
${data.followUp}

${APP_SIGNATURE}`

  return { subject, body }
}

export const sendEmailWithTemplate = (template: EmailTemplate) => {
  const mailtoLink = `mailto:?subject=${encodeURIComponent(template.subject)}&body=${encodeURIComponent(template.body)}`
  window.location.href = mailtoLink
}
